# jconvolver configuration
#
#                in  out   partition    maxsize    density
# --------------------------------------------------------
/convolver/new    2   2      4096    44100        1.0

#
# define impulse responses
#
#               in out  gain   delay  offset  length  chan      file  
# ------------------------------------------------------------------------------
#
/impulse/read 1 2 1 0 0 0 1 BRIR_Position_5.wav
/impulse/read 2 2 1 0 0 0 2 BRIR_Position_5.wav
/impulse/read 3 2 1 0 0 0 3 BRIR_Position_5.wav
/impulse/read 4 2 1 0 0 0 4 BRIR_Position_5.wav
/impulse/read 5 2 1 0 0 0 5 BRIR_Position_5.wav
/impulse/read 6 2 1 0 0 0 6 BRIR_Position_5.wav
/impulse/read 7 2 1 0 0 0 7 BRIR_Position_5.wav
/impulse/read 8 2 1 0 0 0 8 BRIR_Position_5.wav
/impulse/read 9 2 1 0 0 0 9 BRIR_Position_5.wav
/impulse/read 10 2 1 0 0 0 10 BRIR_Position_5.wav
/impulse/read 11 2 1 0 0 0 11 BRIR_Position_5.wav
/impulse/read 12 2 1 0 0 0 12 BRIR_Position_5.wav
/impulse/read 13 2 1 0 0 0 13 BRIR_Position_5.wav
/impulse/read 14 2 1 0 0 0 14 BRIR_Position_5.wav
/impulse/read 15 2 1 0 0 0 15 BRIR_Position_5.wav
/impulse/read 16 2 1 0 0 0 16 BRIR_Position_5.wav
/impulse/read 17 2 1 0 0 0 17 BRIR_Position_5.wav
/impulse/read 18 2 1 0 0 0 18 BRIR_Position_5.wav
/impulse/read 19 2 1 0 0 0 19 BRIR_Position_5.wav
/impulse/read 20 2 1 0 0 0 20 BRIR_Position_5.wav
/impulse/read 21 2 1 0 0 0 21 BRIR_Position_5.wav
/impulse/read 22 2 1 0 0 0 22 BRIR_Position_5.wav
/impulse/read 23 2 1 0 0 0 23 BRIR_Position_5.wav
/impulse/read 24 2 1 0 0 0 24 BRIR_Position_5.wav
/impulse/read 1 1 1 0 0 0 25 BRIR_Position_5.wav
/impulse/read 2 1 1 0 0 0 26 BRIR_Position_5.wav
/impulse/read 3 1 1 0 0 0 27 BRIR_Position_5.wav
/impulse/read 4 1 1 0 0 0 28 BRIR_Position_5.wav
/impulse/read 5 1 1 0 0 0 29 BRIR_Position_5.wav
/impulse/read 6 1 1 0 0 0 30 BRIR_Position_5.wav
/impulse/read 7 1 1 0 0 0 31 BRIR_Position_5.wav
/impulse/read 8 1 1 0 0 0 32 BRIR_Position_5.wav
/impulse/read 9 1 1 0 0 0 33 BRIR_Position_5.wav
/impulse/read 10 1 1 0 0 0 34 BRIR_Position_5.wav
/impulse/read 11 1 1 0 0 0 35 BRIR_Position_5.wav
/impulse/read 12 1 1 0 0 0 36 BRIR_Position_5.wav
/impulse/read 13 1 1 0 0 0 37 BRIR_Position_5.wav
/impulse/read 14 1 1 0 0 0 38 BRIR_Position_5.wav
/impulse/read 15 1 1 0 0 0 39 BRIR_Position_5.wav
/impulse/read 16 1 1 0 0 0 40 BRIR_Position_5.wav
/impulse/read 17 1 1 0 0 0 41 BRIR_Position_5.wav
/impulse/read 18 1 1 0 0 0 42 BRIR_Position_5.wav
/impulse/read 19 1 1 0 0 0 43 BRIR_Position_5.wav
/impulse/read 20 1 1 0 0 0 44 BRIR_Position_5.wav
/impulse/read 21 1 1 0 0 0 45 BRIR_Position_5.wav
/impulse/read 22 1 1 0 0 0 46 BRIR_Position_5.wav
/impulse/read 23 1 1 0 0 0 47 BRIR_Position_5.wav
/impulse/read 24 1 1 0 0 0 48 BRIR_Position_5.wav
